sudo: false
language: node_js
node_js: 8.15.1

cache:
  directories: 
    -"node_modules"

before_script:
  - npm update -q
  - npm install

stages:
  - compile
  - tests
  - deploy

jobs:
  include:
    - stage: tests
      name: "unit test"
      script: npm run unit
    - script: npm run e2e
      name: "end to end test"
    - stage: deploy to production
      script: /bin/true
      deploy: heroku
      app: app-ac
      api_key: ${api_key}
      on:
        repo: rodrigoRolim/frontend-ac
        branch: master
    - stage: test production
      scritp: "curl https://app-ac.herokuapp.com"